# Generated by Django 3.1.5 on 2021-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
